### ISSUE TITLE
merge branches

### ISSUE THREAD

**Issue by kibaekkim** [kibaekkim/DualDecomposition.jl#1]
@michel2323 @youngdae Can we merge branches `master` and `julia0.4.7`, and merge branches `mpi` and `mpi-julia0.4.7`? How about creating directory `legacy` to put stuff from `julia0.4.7`, checking `VERSION` and redirecting to the directory (whenever needed)?

**Comment by kibaekkim** [comment]
@michel2323 persuaded me that the current setting is better. Agreeing with that, I am closing this.

**Comment by michel2323** [comment]
@youngdae also merged today. so the mpi branch and master should be in sync and all changes were backported from julia 0.4.7 branch.
