### ISSUE TITLE
Attempting to use MPI for non-MPI code

### ISSUE THREAD

**Issue by wzhangw** [kibaekkim/DualDecomposition.jl#11]
The following message sometimes shows up when running code that does not initialize MPI, and the program is killed:

"Attempting to use an MPI routine after finalizing MPICH"

**Comment by kibaekkim** [comment]
@wzhangw Just for note, it would be great if you can find a reproducible case.

**Comment by kibaekkim** [comment]
It may be safer to let user initialize and finalize MPI: https://github.com/kibaekkim/DualDecomposition.jl/blob/master/src/LagrangeDual.jl#L26

**Comment by kibaekkim** [comment]
@wzhangw We can reopen this, once you run into the issue again.
