### ISSUE TITLE
Multistage stochastic optimization example

### ISSUE THREAD

**Issue by kibaekkim** [kibaekkim/DualDecomposition.jl#13]
@hideakiv Can you add your multistage stochastic optimization example (not the DRO one) to this repo (in `example` directory)? You can create a PR.

**Comment by hideakiv** [comment]
@kibaekkim The data structure is dependent on DRMSMIP.jl, which is dependent on the DRMS branch. We may have to merge these.

**Comment by kibaekkim** [comment]
@hideakiv As we discussed, please add the multistage example by using the package as it is, not by using the DRO extension.
