### ISSUE TITLE
MPI error

### ISSUE THREAD

**Issue by CanLi1** [kibaekkim/DualDecomposition.jl#17]
I was using dual decomposition to solve a problem a encountered the following error

Attempting to use an MPI routine after finalizing MPICH

It didn't tell which line the error was triggered. The error can be reproduced by running the file test_DD.jl. The run!() function of dual decomposition was used in file util.jl

https://bitbucket.org/kibaekkim/energystorage/commits/773d73b383de54779c66e9c6372bec4f7d67c387

**Comment by kibaekkim** [comment]
This must have been resolved by #15. also in version `0.1.1`. I also confirmed that by running `test_DD.jl`. Thanks!
