### ISSUE TITLE
cannot use ADMM.jl

### ISSUE THREAD

**Issue by kibaekkim** [kibaekkim/DualDecomposition.jl#2]
@youngdae I cannot do `using ADMM`. The module `ADMM` is not accessible, I think.

**Comment by youngdae** [comment]
@kibaekkim Did you add the JuDD.git/src directory in your LOAD_PATH? For example, I've added it in .julia/config/startup.jl as follows:

push!(LOAD_PATH, "/Users/youngdae/git-repos/kibaek/JuDD.git/src")

**Comment by kibaekkim** [comment]
resolved
