### ISSUE TITLE
mpi branch not working

### ISSUE THREAD

**Issue by kibaekkim** [kibaekkim/DualDecomposition.jl#3]
With `mpi` branch, we cannot run with more than a process. If we run with a process, the dual decomposition does not converge.

**Comment by michel2323** [comment]
Which example is that with how many processes?

You need:

- structjump branch of BundleMethod
- [duals branch of StructJuMPSolverInterface](https://github.com/Argonne-National-Laboratory/StructJuMPSolverInterface.jl/tree/duals)
- and run without a remainer in the partitioning. (can be fixed)
- the mpi branch does only support ProximalDualMethod
I can work on this in the GO Challenge code.

**Comment by kibaekkim** [comment]
I have tested `dcap.jl` with `use_admm=false` in [line 104](https://github.com/kibaekkim/JuDD.jl/blob/mpi/examples/dcap.jl#L104).

```bash
diff --git a/examples/dcap.jl b/examples/dcap.jl
index 0ab3ed9..9db0535 100644
--- a/examples/dcap.jl
+++ b/examples/dcap.jl
@@ -101,4 +101,4 @@ end
 # return the array of nonanticipativity variables
 nonanticipativity_vars() = [:x,:u]

-main_dcap(2,3,3,20; use_admm=true)
+main_dcap(2,3,3,20; use_admm=false)
```

Here is my environment:
- `julia1.1.0`
- `BundleMethod#structjump`
- `JuDD#mpi`
- `StructJuMP#julia0.7`
- `StructJuMPSolverInterface#duals`

I do not see any bundle is added to the master problem.

**Comment by michel2323** [comment]
It runs fine here in 19 iterations with the latest commit.

**Comment by kibaekkim** [comment]
works now
