### ISSUE TITLE
Cannot use JuDD.jl - MPI and StructJuMPSolverInterface.jl not loading

### ISSUE THREAD

**Issue by puneetchitkara** [kibaekkim/DualDecomposition.jl#4]
I have Julia version 1.2.0 and JuMP version 0.19.2. I understand that JuDD.jl is not compatible with this version of JuMP. I tried the following: (but still does not work):

Went to Pkg>
Pkg> activate tutorial

Then the following happened:
(tutorial) pkg> add https://github.com/kibaekkim/BundleMethod.jl.git
  Updating git-repo `https://github.com/kibaekkim/BundleMethod.jl.git`
[ Info: Assigning UUID 03bf20df-d8a0-5746-8978-d623d54f279b to BundleMethod
  Updating git-repo `https://github.com/kibaekkim/BundleMethod.jl.git`
 Resolving package versions...
  Updating `C:\Users\...\tutorial\Project.toml`
  [03bf20df] + BundleMethod v0.0.0 #master (https://github.com/kibaekkim/BundleMethod.jl.git)
  Updating `C:\Users\...\tutorial\Manifest.toml`
  [03bf20df] + BundleMethod v0.0.0 #master (https://github.com/kibaekkim/BundleMethod.jl.git)

(tutorial) pkg> add "https://github.com/kibaekkim/JuDD.jl", rev="mpi"
   Cloning git-repo `https://github.com/kibaekkim/JuDD.jl`
  Updating git-repo `https://github.com/kibaekkim/JuDD.jl`
  Updating git-repo `https://github.com/kibaekkim/JuDD.jl`
   Cloning git-repo `,`
ERROR: failed to clone from ,, error: GitError(Code:ERROR, Class:Net, unsupported URL protocol)

(tutorial) pkg> add https://github.com/kibaekkim/JuDD.jl
  Updating git-repo `https://github.com/kibaekkim/JuDD.jl`
  Updating git-repo `https://github.com/kibaekkim/JuDD.jl`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package StructJuMPSolverInterface [7a00d66c]:
 StructJuMPSolverInterface [7a00d66c] log:
 ├─StructJuMPSolverInterface [7a00d66c] has no known versions!
 └─restricted to versions * by JuDD [23e7f524] — no versions left
   └─JuDD [23e7f524] log:
     ├─possible versions are: 0.0.0 or uninstalled
     └─JuDD [23e7f524] is fixed to version 0.0.0

(tutorial) pkg> add https://github.com/StructJuMP/StructJuMPSolverInterface.jl.git
  Updating git-repo `https://github.com/StructJuMP/StructJuMPSolverInterface.jl.git`
[ Info: Assigning UUID 7a00d66c-3a07-54c1-b1e3-917bd47595ee to StructJuMPSolverInterface
  Updating git-repo `https://github.com/StructJuMP/StructJuMPSolverInterface.jl.git`
 Resolving package versions...
 Installed MPI ────────────── v0.10.0
 Installed MathOptInterface ─ v0.9.1
  Updating `C:\Users\...\tutorial\Project.toml`
  [7a00d66c] + StructJuMPSolverInterface v0.0.0 #master (https://github.com/StructJuMP/StructJuMPSolverInterface.jl.git)
  Updating `C:\Users\...\tutorial\Manifest.toml`
  [6e4b80f9] + BenchmarkTools v0.4.2
  [b6b21f68] + Ipopt v0.6.0
  [682c06a0] + JSON v0.21.0
  [da04e1cc] + MPI v0.10.0
  [b8f27783] + MathOptInterface v0.9.1
  [69de0a69] + Parsers v0.3.6
  [ae029012] + Requires v0.5.2
  [7a00d66c] + StructJuMPSolverInterface v0.0.0 #master (https://github.com/StructJuMP/StructJuMPSolverInterface.jl.git)
  Building MPI → `C:\Users\...\.julia\packages\MPI\RzbIV\deps\build.log`
┌ Error: Error building `MPI`:
│ ERROR: LoadError: No MPI library found.
│ Ensure an MPI implementation is loaded, or set the `JULIA_MPI_PATH` variable.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\...\.julia\packages\MPI\RzbIV\deps\build.jl:42
│  [3] include at .\boot.jl:328 [inlined]
│  [4] include_relative(::Module, ::String) at .\loading.jl:1094
│  [5] include(::Module, ::String) at .\Base.jl:31
│  [6] include(::String) at .\client.jl:431
│  [7] top-level scope at none:5
│ in expression starting at C:\Users\...\.julia\packages\MPI\RzbIV\deps\build.jl:41
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647

(tutorial) pkg> add https://github.com/JuliaParallel/MPI.jl.git
   Cloning git-repo `https://github.com/JuliaParallel/MPI.jl.git`
  Updating git-repo `https://github.com/JuliaParallel/MPI.jl.git`
  Updating git-repo `https://github.com/JuliaParallel/MPI.jl.git`
 Resolving package versions...
  Updating `C:\Users\...\tutorial\Project.toml`
  [da04e1cc] + MPI v0.10.0 #master (https://github.com/JuliaParallel/MPI.jl.git)
  Updating `C:\Users\...\tutorial\Manifest.toml`
  [da04e1cc] ~ MPI v0.10.0 ⇒ v0.10.0 #master (https://github.com/JuliaParallel/MPI.jl.git)
  Building MPI → `C:\Users\...\.julia\packages\MPI\Dw1uR\deps\build.log`
┌ Error: Error building `MPI`:
│ ERROR: LoadError: No MPI library found.
│ Ensure an MPI implementation is loaded, or set the `JULIA_MPI_PATH` variable.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at C:\Users\...\.julia\packages\MPI\Dw1uR\deps\build.jl:42
│  [3] include at .\boot.jl:328 [inlined]
│  [4] include_relative(::Module, ::String) at .\loading.jl:1094
│  [5] include(::Module, ::String) at .\Base.jl:31
│  [6] include(::String) at .\client.jl:431
│  [7] top-level scope at none:5
│ in expression starting at C:\Users\...\.julia\packages\MPI\Dw1uR\deps\build.jl:41
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647

Finally, MPI.jl and StructJuMPSolverInterface.jl is not loading

**Comment by kibaekkim** [comment]
You must not have MPI library, a required library that is used in `MPI.jl`. You seem to use a Windows OS, for which I do not have tested the package. You can try downloading and installing the library from https://www.mpich.org/downloads/.

**Comment by kibaekkim** [comment]
This package has been updated, but the mpi part is not yet done. For parallel runs, please check out: https://github.com/kibaekkim/DSPopt.jl
