### ISSUE TITLE
Fix ADMM

### ISSUE THREAD

**Issue by kibaekkim** [kibaekkim/DualDecomposition.jl#5]
While updating the package, I have moved the ADMM part to a separate branch. @youngdae please feel free to update the method and make a PR.

**Comment by youngdae** [comment]
By updating, does it mean making it compatible with MOI?

**Comment by kibaekkim** [comment]
The package relies on `JuMP`, not on `MOI`. Compatibility information is available here: https://github.com/kibaekkim/DualDecomposition.jl/blob/master/Project.toml
